services:
    Inspector\Symfony\Bundle\Command\InspectorTestCommand:
        arguments:
          [ '@Inspector\Inspector', '@logger', '@Inspector\Configuration' ]
        tags:
            - { name: 'console.command', command: 'inspector:test' }

    Inspector\Symfony\Bundle\Command\InspectorPulseCommand:
        arguments:
          [ '@Inspector\Inspector' ]
        tags:
            - { name: 'console.command', command: 'inspector:pulse' }

