inspector:
    ingestion_key: '%env(INSPECTOR_INGESTION_KEY)%'
    enabled: true
    ignore_urls:
        - '_wdt'
        - '_profiler'
        - '_profiler_home'
        - '_profiler_search'
        - '_profiler_search_bar'
        - '_profiler_phpinfo'
        - '_profiler_search_results'
        - '_profiler_open_file'
        - '_profiler_router'
        - '_profiler_exception'
        - '_profiler_exception_css'
