inspector:
    ingestion_key: '%env(INSPECTOR_INGESTION_KEY)%'
    url: https://ingest.inspector.dev
    enabled: true
    unhandled_exceptions: true
    query: true
    query_bindings: false
    user: true
    transport: async
    server_sampling_ratio: 0
    ignore_routes: []
    ignore_commands: []


